/*
 * Kagi API
 *
 * The Kagi API provides programmatic access to data that powers our search results & more.   Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more.  ### Official Client Libraries  We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library.  - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust)  ### API Status  **The v1 API is currently in preview to early access testers.**  Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available.  See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details.  ### Pricing  See our [API Pricing](https://kagi.com/api/pricing) page for standard rates.  ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas)  ### Discord  Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs! 
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kagi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchRequestLens : Inline description of a lens to apply to the search. Options supplied by the lens take precedence over those supplied by the user in their search terms (e.g., `site:` operators), allowing you to restrict the scope of the search to return more relevant results in specific applications.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchRequestLens {
    /// Search only these domains.
    #[serde(rename = "sites_included", skip_serializing_if = "Option::is_none")]
    pub sites_included: Option<Vec<String>>,
    /// Exclude these domains from the search.
    #[serde(rename = "sites_excluded", skip_serializing_if = "Option::is_none")]
    pub sites_excluded: Option<Vec<String>>,
    /// Return only results containing these keywords.
    #[serde(rename = "keywords_included", skip_serializing_if = "Option::is_none")]
    pub keywords_included: Option<Vec<String>>,
    /// Exclude results containing these keywords.
    #[serde(rename = "keywords_excluded", skip_serializing_if = "Option::is_none")]
    pub keywords_excluded: Option<Vec<String>>,
    /// A specific file type to search for. (e.g., `pdf`)
    #[serde(rename = "file_type", skip_serializing_if = "Option::is_none")]
    pub file_type: Option<String>,
    /// Filters for web pages that have been updated or published *after* the given date.
    #[serde(rename = "time_after", skip_serializing_if = "Option::is_none")]
    pub time_after: Option<chrono::NaiveDate>,
    /// Filters for web pages that have been updated or published *before* the given date.
    #[serde(rename = "time_before", skip_serializing_if = "Option::is_none")]
    pub time_before: Option<chrono::NaiveDate>,
    /// Filters for web pages that have been updated or published in the given interval, relative to today's date.
    #[serde(rename = "time_relative", skip_serializing_if = "Option::is_none")]
    pub time_relative: Option<TimeRelative>,
    /// Requests results localized to a specific region. Can be any valid [ISO-3166-1 Alpha-2 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements), or the special value `no_region`, that will try to get the most general results possible.
    #[serde(rename = "search_region", skip_serializing_if = "Option::is_none")]
    pub search_region: Option<String>,
}

impl SearchRequestLens {
    /// Inline description of a lens to apply to the search. Options supplied by the lens take precedence over those supplied by the user in their search terms (e.g., `site:` operators), allowing you to restrict the scope of the search to return more relevant results in specific applications.
    pub fn new() -> SearchRequestLens {
        SearchRequestLens {
            sites_included: None,
            sites_excluded: None,
            keywords_included: None,
            keywords_excluded: None,
            file_type: None,
            time_after: None,
            time_before: None,
            time_relative: None,
            search_region: None,
        }
    }
}
/// Filters for web pages that have been updated or published in the given interval, relative to today's date.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TimeRelative {
    #[serde(rename = "day")]
    Day,
    #[serde(rename = "week")]
    Week,
    #[serde(rename = "month")]
    Month,
}

impl Default for TimeRelative {
    fn default() -> TimeRelative {
        Self::Day
    }
}

