/*
 * Kagi API
 *
 * The Kagi API provides programmatic access to data that powers our search results & more.   Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more.  ### Official Client Libraries  We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library.  - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust)  ### API Status  **The v1 API is currently in preview to early access testers.**  Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available.  See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details.  ### Pricing  See our [API Pricing](https://kagi.com/api/pricing) page for standard rates.  ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas)  ### Discord  Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs! 
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kagi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchRequest : Used to upload the search query
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchRequest {
    /// Search query to run.
    #[serde(rename = "query")]
    pub query: String,
    /// Type of results to return.
    #[serde(rename = "workflow", skip_serializing_if = "Option::is_none")]
    pub workflow: Option<Workflow>,
    /// **(EXPERIMENTAL)** Format to serialize the API response as. The exact contents and structure of markdown output is still being worked on - please send your feedback!
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<Format>,
    /// Lens to apply to the search. Can be a built-in lens's identifier or a lens ID as shown on https://kagi.com/settings/lenses when a lens is set to be shareable. Can be just the ID portion of the URL (`https://kagi.com/lenses/ID`) or the full URL.
    #[serde(rename = "lens_id", skip_serializing_if = "Option::is_none")]
    pub lens_id: Option<String>,
    #[serde(rename = "lens", skip_serializing_if = "Option::is_none")]
    pub lens: Option<Box<models::SearchRequestLens>>,
    /// Number of seconds to allow for collecting search results. Lower values will return results more quickly, but may be lower quality or inconsistent between calls. If omitted, will use the latest recommended value by Kagi.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<f64>,
    /// Page number for paginated results. Must be between 1 and 10.
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    /// Maximum number of results to return. Must be between 1 and 1024.  **NOTE:** This does not change the amount of results requested, it only limits the maximum amount returned. If omitted, the API always gives you the most results we can get in a single pass. 
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Box<models::SearchRequestFilters>>,
    #[serde(rename = "extract", skip_serializing_if = "Option::is_none")]
    pub extract: Option<Box<models::SearchRequestExtract>>,
    /// Whether safe search is enabled, omitting potentially NSFW content.
    #[serde(rename = "safe_search", skip_serializing_if = "Option::is_none")]
    pub safe_search: Option<bool>,
    #[serde(rename = "personalizations", skip_serializing_if = "Option::is_none")]
    pub personalizations: Option<Box<models::SearchRequestPersonalizations>>,
}

impl SearchRequest {
    /// Used to upload the search query
    pub fn new(query: String) -> SearchRequest {
        SearchRequest {
            query,
            workflow: None,
            format: None,
            lens_id: None,
            lens: None,
            timeout: None,
            page: None,
            limit: None,
            filters: None,
            extract: None,
            safe_search: None,
            personalizations: None,
        }
    }
}
/// Type of results to return.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Workflow {
    #[serde(rename = "search")]
    Search,
    #[serde(rename = "images")]
    Images,
    #[serde(rename = "videos")]
    Videos,
    #[serde(rename = "news")]
    News,
    #[serde(rename = "podcasts")]
    Podcasts,
}

impl Default for Workflow {
    fn default() -> Workflow {
        Self::Search
    }
}
/// **(EXPERIMENTAL)** Format to serialize the API response as. The exact contents and structure of markdown output is still being worked on - please send your feedback!
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "json")]
    Json,
    #[serde(rename = "markdown")]
    Markdown,
}

impl Default for Format {
    fn default() -> Format {
        Self::Json
    }
}

