/*
 * Kagi API
 *
 * The Kagi API provides programmatic access to data that powers our search results & more.  Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more. ### Official Client Libraries We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library. - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust) ### API Status Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available. See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details. ### Pricing See our [API Pricing](https://kagi.com/api/pricing) page for standard rates. ### GitHub Discussions This is the preferred venue for bug reports and feature requests. - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas) ### Discord Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs!
 *
 * The version of the OpenAPI document: v1
 * Contact: support@kagi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchRequestPersonalizationsDomainsInner {
    /// The domain to personalize (e.g., \"example.com\").
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Bias value to apply to results from this domain.
    #[serde(rename = "bias", skip_serializing_if = "Option::is_none")]
    pub bias: Option<f64>,
}

impl SearchRequestPersonalizationsDomainsInner {
    pub fn new() -> SearchRequestPersonalizationsDomainsInner {
        SearchRequestPersonalizationsDomainsInner {
            domain: None,
            bias: None,
        }
    }
}

